### ISSUE TITLE
mac build error: use 'template' keyword to treat 'remove_object' as a dependent template name

### ISSUE THREAD

**Issue by robsussman** [pmed/v8pp#10]
When building with xcode (I have 6.1.1) I get the following error: 

```
/Users/rob/Documents/src/test/v8pp/v8pp/class.hpp:226:23: error: use 'template' keyword to treat 'remove_object' as a dependent template name
                                instance(isolate).remove_object<T>(isolate, object, nullptr);
                                                  ^
                                                  template1
```
If I make this change, adding the template keywoard, then it builds fine: 
v8pp/class.hpp, line 226:
```
- instance(isolate).remove_object<T>(isolate, object, nullptr);
+ instance(isolate).template remove_object<T>(isolate, object, nullptr);
```
Thanks for taking a look!

**Comment by pmed** [comment]
Thanks! I'll fix it. Either you may make a pull request :-)

**Comment by robsussman** [comment]
Thanks! Wasn't sure a pull request was worth it for this simple fix. But, I can do if you like.  :)

**Comment by robsussman** [comment]
Okay, I just created a pull request. Please let me know if I messed it up.  :)

Thanks!

**Comment by pmed** [comment]
Merged, thanks. I can't check it right now, but sure everything is ok.
