### ISSUE TITLE
I  follow the README and want to make a V8PP_PLUGIN,but these are some errors

### ISSUE THREAD

**Issue by zxbzswxr** [pmed/v8pp#101]
I build the project and export file.dll and console.dll ,but It  cant work in node.js 
![image](https://user-images.githubusercontent.com/18022264/47012282-7db28e00-d176-11e8-91b9-da9d9b54bddd.png) 
what's wrong with it ? Can anyone help me??
Let me initiate a magic summon @pmed  My God HELP!!!!!

**Comment by pmed** [comment]
Hi,

`V8PP_PLUGIN`, `file`, and `console` plugins could be used   when the V8 is embedded into a custom application.

To create Node.js **addons** with `v8pp` you'd better to look at the corresponding [documentation chapter](https://github.com/pmed/v8pp/blob/master/docs/addons.md) and code examples at https://github.com/pmed/v8pp/tree/master/examples

**Comment by pmed** [comment]
`V8` is just a JavaScript engine library that could be used in any C++ application, and Node.js is one of them.

The `v8pp` library allows to create native C++ Node.js **addons**, as described in Node.js  and the documentation link above.

There is also a simple **plugins** support in the `v8pp` library, mostly for demonstration and test purposes, it's implemented in [`v8pp::context`](https://github.com/pmed/v8pp/blob/master/docs/context.md) class.
 

>

**Comment by zxbzswxr** [comment]
@pmed   is these any tutorial about how to use v8pp::context  classs in detail, better accomplishing
 wrapping a custom C++  class
