### ISSUE TITLE
Debug check failed: platform

### ISSUE THREAD

**Issue by aj3423** [pmed/v8pp#103]
I downloaded the v8-v141-x86 package using NuGet,  compiled v8pp with this "v8-v141-x86.7.3.492.21" prebuilt v8 header file. Then I create a simple test program 

    #include <v8pp/context.hpp>
    int main() {
        v8pp::context context;
    }

It's fine for compiling and linking, but error happens when running:

    #
    # Fatal error in .\../../../../../src/v8.cc, line 125
    # Debug check failed: platform.
    #
    #
    #
    #FailureMessage Object: 012FF80C

My environment:  Win10 pro 64-bit, vs2017 Community.  How to fix it? Thanks.

**Comment by pmed** [comment]
Hi

You have to initialize V8 before usage, please refer [V8 docs](https://v8.dev/docs/embed) or [v8pp test program](https://github.com/pmed/v8pp/blob/master/test/main.cpp#L112-L116)

And do no forget to finalise V8 at the end of your program, like in v8pp test program [does it](https://github.com/pmed/v8pp/blob/master/test/main.cpp#L144-L146)
