### ISSUE TITLE
Cannot use std converters with shared_ptr_traits

### ISSUE THREAD

**Issue by jcmonnin** [pmed/v8pp#105]
Hi,

I have recently tried to update the v8 and v8pp versions in my project. When having a class bound by v8pp using `shared_ptr_traits` it looks like it's impossible to use the converters from the std datatypes (for example the automatic conversion from JavaScript array to std::vector<T>). This problem didn't happen on the old version where the shared_ptr usage was given by a flag rather than the type traits class.

This commit gives a test case for that problem: jcmonnin@1d4b7ecbb241dd248629aee8ea65ac591635e0fa

It gives following compile error:

    In file included from test/test_class.cpp:10:
    ./v8pp/class.hpp: In instantiation of ‘class v8pp::class_<std::vector<int>, v8pp::shared_ptr_traits>’:
    ./v8pp/convert.hpp:578:62:   required from ‘static v8pp::convert<std::shared_ptr<_Tp>, typename std::enable_if<v8pp::is_wrapped_class<T>::value>::type>::from_type v8pp::convert<std::shared_ptr<_Tp>, typename std::enable_if<v8pp::is_wrapped_class<T>::value>::type>::from_v8(v8::Isolate*, v8::Local<v8::Value>) [with T = const std::vector<int>; v8pp::convert<std::shared_ptr<_Tp>, typename std::enable_if<v8pp::is_wrapped_class<T>::value>::type>::from_type = std::shared_ptr<const std::vector<int> >]’
    ./v8pp/convert.hpp:604:71:   required from ‘static T& v8pp::convert<T, v8pp::ref_from_shared_ptr>::from_v8(v8::Isolate*, v8::Local<v8::Value>) [with T = const std::vector<int>; v8pp::convert<T, v8pp::ref_from_shared_ptr>::from_type = const std::vector<int>&]’
    ./v8pp/call_from_v8.hpp:64:45:   required from ‘static decltype (v8pp::detail::call_from_v8_traits<F, Offset>::arg_convert<Index, Traits>::from_v8(declval<v8::Isolate*>(), declval<v8::Local<v8::Value> >())) v8pp::detail::call_from_v8_traits<F, Offset>::arg_from_v8(const v8::FunctionCallbackInfo<v8::Value>&) [with long unsigned int Index = 0; Traits = v8pp::shared_ptr_traits; F = void (X::*)(const std::vector<int>&); long unsigned int Offset = 0; decltype (v8pp::detail::call_from_v8_traits<F, Offset>::arg_convert<Index, Traits>::from_v8(declval<v8::Isolate*>(), declval<v8::Local<v8::Value> >())) = const std::vector<int>&; v8pp::detail::call_from_v8_traits<F, Offset>::arg_convert<Index, Traits> = v8pp::convert<const std::vector<int>, v8pp::ref_from_shared_ptr>]’
    ./v8pp/call_from_v8.hpp:132:70:   required from ‘typename v8pp::detail::function_traits<F>::return_type v8pp::detail::call_from_v8_impl(T&, F&&, const v8::FunctionCallbackInfo<v8::Value>&, CallTraits, v8pp::detail::index_sequence<Indices ...>) [with Traits = v8pp::shared_ptr_traits; T = X; F = void (X::*)(const std::vector<int>&); CallTraits = v8pp::detail::call_from_v8_traits<void (X::*)(const std::vector<int>&), 0>; long unsigned int ...Indices = {0}; typename v8pp::detail::function_traits<F>::return_type = void; v8pp::detail::index_sequence<Indices ...> = v8pp::detail::integer_sequence<long unsigned int, 0>]’
    ./v8pp/call_from_v8.hpp:185:34:   required from ‘typename v8pp::detail::function_traits<F>::return_type v8pp::detail::call_from_v8(T&, F&&, const v8::FunctionCallbackInfo<v8::Value>&) [with Traits = v8pp::shared_ptr_traits; T = X; F = void (X::*)(const std::vector<int>&); typename v8pp::detail::function_traits<F>::return_type = void]’
    ./v8pp/function.hpp:139:44:   required from ‘typename v8pp::detail::function_traits<F>::return_type v8pp::detail::invoke(const v8::FunctionCallbackInfo<v8::Value>&, std::true_type) [with Traits = v8pp::shared_ptr_traits; F = void (X::*)(const std::vector<int>&); typename v8pp::detail::function_traits<F>::return_type = void; std::true_type = std::integral_constant<bool, true>]’
    ./v8pp/function.hpp:147:19:   required from ‘void v8pp::detail::forward_ret(const v8::FunctionCallbackInfo<v8::Value>&, std::true_type) [with Traits = v8pp::shared_ptr_traits; F = void (X::*)(const std::vector<int>&); std::true_type = std::integral_constant<bool, true>]’
    ./v8pp/function.hpp:168:25:   required from ‘void v8pp::detail::forward_function(const v8::FunctionCallbackInfo<v8::Value>&) [with Traits = v8pp::shared_ptr_traits; F = void (X::*)(const std::vector<int>&)]’
    ./v8pp/class.hpp:505:59:   required from ‘typename std::enable_if<std::is_member_function_pointer<Method>::value, v8pp::class_<T, Traits>&>::type v8pp::class_<T, Traits>::set(const char*, Method, v8::PropertyAttribute) [with Method = void (X::*)(const std::vector<int>&); T = X; Traits = v8pp::shared_ptr_traits; typename std::enable_if<std::is_member_function_pointer<Method>::value, v8pp::class_<T, Traits>&>::type = v8pp::class_<X, v8pp::shared_ptr_traits>&]’
    test/test_class.cpp:134:2:   required from ‘void test_class_() [with Traits = v8pp::shared_ptr_traits]’
    test/test_class.cpp:399:39:   required from here
    ./v8pp/class.hpp:430:16: error: static assertion failed: T must be a user-defined class
      static_assert(is_wrapped_class<T>::value, "T must be a user-defined class");
                    ^~~~~~~~~~~~~~~~~~~
    In file included from ./v8pp/class.hpp:737,
                     from test/test_class.cpp:10:

**Comment by jcmonnin** [comment]
I've checked `version-2.0` and the problem is also reproducible on this branch. To convert the JavaScript array to std::vector<int>, it picks:

    template<typename T>
    struct convert<T, ref_from_shared_ptr>

instead of

    // convert Array <-> std::vector
    template<typename T, typename Alloc>
    struct convert<std::vector<T, Alloc>>

`is_wrapped_class` returning `std::false_type` is defined by the library for `std::vector`

    template<typename T, typename Alloc>
    struct is_wrapped_class<std::vector<T, Alloc>> : std::false_type {};

**Comment by pmed** [comment]
HI @jcmonnin,

Thank you for the report!

I've fixed this issue on the master branch, am working on backporting the fix to the `version- 2.0` branch.

**Comment by jcmonnin** [comment]
Thanks for the quick fix.

**Comment by jcmonnin** [comment]
I tired to switch to version 2.0 but got stuck on that error. Applying the patch as such on 2.0 doesn't work and I haven't been able to fix it. Do you have any work in progress for that?

**Comment by pmed** [comment]
Hi @jcmonnin,

yes, this fix was not backported to `version-2.0` due to differences with `master` branch.

I've merged the changes to `version-2.0` just now.

**Comment by jcmonnin** [comment]
Thanks a lot for fixing version-2.0 too. I now can successfully change my project to use version-2.0. I have a some minor warning fixes on separate PR.
