### ISSUE TITLE
Make it work with newer v8 versions

### ISSUE THREAD

**Issue by ayles** [pmed/v8pp#120]
I'm using `v8pp` with `V8 7.7.214`, and there is following problems:

`convert.hpp line 182:`

    return value->BooleanValue(isolate->GetCurrentContext()).FromJust();

should be changed to

    return value->BooleanValue(isolate);

`throw_ex.ipp lines 7 and 13` - `.ToLocalChecked()` needed.

So it will be cool to add some `#if's` on V8 version to fix this.
I'm not so deep into V8 and it's change history so I can't do it right =)

**Comment by pmed** [comment]
Hi,

Thanks for the reporting. Yes, that deprecated `BooleanValue()` overload was removed in V8 7.6 version. I have definitely to fix this.

Duplicates: #117

**Comment by pmed** [comment]
Fixed by @jacobsologub in PR #123
