### ISSUE TITLE
Factory in c++17 branch

### ISSUE THREAD

**Issue by ayles** [pmed/v8pp#126]
In our project we need to implement extension constructor with `FunctionCallbackInfo` as argument, but it is not possible without removed `factory`. We can override `Traits` (alot of work) or pass custom function to `ctor` (alot of work + necessity to call `AdjustAmountOfExternalAllocatedMemory` in this function).
So maybe there should be some adjustments in API?

**Comment by pmed** [comment]
The `factory` was removed in this branch because it duplicates the custom `ctor` function argument for the `class_::ctor<>()`. 

Honestly I can't imagine a lot of work comparing to the prior `factory` usage.
