### ISSUE TITLE
MSVS 2019 Warning C5046

### ISSUE THREAD

**Issue by kervinpierre** [pmed/v8pp#129]
I'm attempting to build with MSVS2019.  I understand it's not supported as yet but trying my luck anyhow.

`4>    I:\src\v8pp\git\v8pp\utility.hpp(155,25): error C2220: the following warning is treated as an error
4>    I:\src\v8pp\git\v8pp\utility.hpp(155,25): warning C5046: 'v8pp::detail::is_callable_impl<v8pp::property_<int (__thiscall test_multiple_inheritance::B::* )(void),int (__thiscall test_multiple_inheritance::B::* )(void)>,true>::fallback::operator ()': Symbol involving type with internal linkage not defined
4>    I:\src\v8pp\git\v8pp\utility.hpp(155,25): message : to simplify migration, consider the temporary use of /Wv:18 flag with the version of the compiler with which you used to build without warnings
`
This is the only warning I've seen so far.  And with warnings treated as errors, the build fails.

Does anyone have insight into fixing this warning?  I'm trying not to ignore an entire class of errors as the message suggests.

**Comment by pmed** [comment]
Hi,

which v8pp version do you use? I tried the fresh master and it has no such warning.
