### ISSUE TITLE
CMake support 

### ISSUE THREAD

**Issue by pmed** [pmed/v8pp#138]
Add CMakeLists.txt to build the library with different configuration options, those are currently available in `config.h`.

Make it ready to publish in a C++ package manager (e.g. vcpkg, Conan)

- [x] CMake project with library, tests, samples
-  ~~Node.js examples~~ t's not worth it right now 
- [x] Add build options and instructions to README.md

**Comment by paulo-coutinho** [comment]
Hi,

It was done?

Thanks

**Comment by YarikTH** [comment]
@pmed Do you have any interest in CMake support? I can polish my implementation and make a PR.

**Comment by paulo-coutinho** [comment]
To me will be nice.

But im not the owner :p

**Comment by Segfaultd** [comment]
Thank you for implementing this, really needed 🙏🏻

**Comment by pmed** [comment]
Done in #173
