### ISSUE TITLE
More of a request than a issue.

### ISSUE THREAD

**Issue by amadlover** [pmed/v8pp#141]
Would be able to create examples of 

1. Expose objects to from c++ to js
2. Expose functions from c++ to js.
3. Expose types from c++ to js.

in plain v8.

Been at it since last week, with little success.

Cheers
Nihal Kenkre.

**Comment by amadlover** [comment]
like an updated version of https://www.github.com/ruby0x1/v8-tutorials

thank you

**Comment by pmed** [comment]
Hi,

have you already seen `examples`, and `docs` directories in the project? There are also some examples at GitHub pages documentation: http://pmed.github.io/v8pp/

**Comment by amadlover** [comment]
Hello Pavel.

Yes i attempted to go through the examples. I am not very proficient with templates thus far, so i am looking for resources to get me started with using V8 from the ground floor.

I have been using the v8-nuget repo for my current development on windows. Thank you for the pre built binaries !!!

This request is more to do to with vanilla v8 examples and not v8pp.

Best regards.
Nihal Kenkre.

**Comment by amadlover** [comment]
Hello.

I am starting to get a hang of things as of today.

So i will close this for now.

Thank for the nuget.

Nihal Kenkre.
