### ISSUE TITLE
support for v8 snapshot

### ISSUE THREAD

**Issue by syabyr** [pmed/v8pp#152]
Hi V8pp Team.

In some situation I want to load v8 snapshot in v8pp based project
Is it possible to add this feature?

thanks.

**Comment by jacobsologub** [comment]
Information about snapshots:
https://v8.dev/blog/custom-startup-snapshots

If you are using `v8pp::context` and currently not passing in an `v8::Isolate` then you'd need to do that by setting up your own `v8::Isolate` with a configured `v8::Isolate::CreateParams` that has a snapshot blob.

https://github.com/pmed/v8pp/blob/c6caf79e401df4d982857d79b4ba23f57f0a7b52/v8pp/context.cpp#L167

**Comment by syabyr** [comment]
After some trying,I found it`s not easy to create a snapshot with v8pp.
some external reference should be passed when creating isolate,such as:
reinterpret_cast<intptr_t>(v8pp::module::var_set<int>),
reinterpret_cast<intptr_t>(v8pp::module::var_set<std::string>)

but there still some external reference can not be found:
Unknown external reference 0x20f6000.
<unresolved>
Program received signal SIGILL, Illegal instruction.
[Switching to Thread 0x7fffedca3700 (LWP 31228)]

(gdb) p (char*)0x20f6000
$10 = 0x20f6000 "\240\210\021\001"
