### ISSUE TITLE
run file.js error

### ISSUE THREAD

**Issue by gocpplua** [pmed/v8pp#155]
when run file.js：
```
SENSETIME\chenqi1@cn0314000510l:/data/3rdparty/v8pp$ ./v8pp_test test/file.js 
Segmentation fault (core dumped)
```

i also use LD_LIBRARY_PATH,but Will still go wrong。

v8:9.2.0

**Comment by pmed** [comment]
Hi,

there is no enough information in the issue. Please provide a minimal complete reproducible example.

**Comment by gocpplua** [comment]
> Hi,
> 
> there is no enough information in the issue. Please provide a minimal complete reproducible example.

I just executed js after compiling, and there was no other information.

**Comment by pmed** [comment]
I tried to run it on a macOS with V8 version 9.0.257.29 installed from brew:

> % DYLD_LIBRARY_PATH=. ./v8pp_test -v --run-tests test/console.js test/file.js

and got the following error:
> V8 version 9.0.257.29
> v8pp version 1.7.0
>
> Fatal error in , line 0
> Embedder-vs-V8 build configuration mismatch. On embedder side pointer compression is DISABLED while on V8 side it's ENABLED.

I added preprocessor defines `V8_COMPRESS_POINTERS` and `V8_31BIT_SMIS_ON_64BIT_ARCH`  to the test program build options, and it runs successfully.
