### ISSUE TITLE
Allow free function from c++ to be registered as a member function in js

### ISSUE THREAD

**Issue by Maxomann** [pmed/v8pp#157]
The goal is to allow free functions (or lambda functions) from c++ to be registered as member functions to a 'v8pp::class_' object.

That allows code like this:

register.cpp:
```cpp
v8pp::class_<nb::Entity> entity_class(isolate);
entity_class.set_fake_member_fn("setPosition", [](nb::Entity& entity, int x, int y){
    entity.getComponent<TransformationComponent>()->setPosition(x, y);
});
```

script.js:
```js
entity.setPosition( 0, 0 );// the entity object is not passed as the first function parameter in js
```

A workaround which makes it possible can be found in [this commit](https://github.com/Maxomann/v8pp/commit/c88080aed97289955f5a19ff0ace1df1d4eb6972).

Would it be possible to add a feature like this to the library?

----------------------------

note: the linked workaround currently requires the lambda to be converted to a function pointer first. So currently it works like this:
register.cpp:
```cpp
v8pp::class_<nb::Entity> entity_class(isolate);
const auto function = [](nb::Entity& entity, int x, int y){
    entity.getComponent<TransformationComponent>()->setPosition(x, y);
}// make sure function does not go out of scope
void(*functionPtr)(nb::Entity&, int x, int y) = function;
entity_class.set_fake_member_fn("setPosition", functionPtr);
```

**Comment by pmed** [comment]
Hi,

it seems you have proposed a feature that has already been implemented on `c++17` branch. That branch was recently merged onto the `master` one.
