### ISSUE TITLE
Deprecated `VisitHandlesWithClassIds` has been removed in v8 10.5.X

### ISSUE THREAD

**Issue by jcmonnin** [pmed/v8pp#181]
It has been removed in https://github.com/v8/v8/commit/4cf204da0a7c59f476bc2ea6622d897f660e22d0

v8pp uses it in `function.hpp`: `external_data::destroy_all`

It does't look trivial to replace it...

**Comment by Aincvy** [comment]
Is there a plan to fix this ?

**Comment by pmed** [comment]
Hi,

I haven't look to this yet. PR are welcome, if you have an idea how to fix it.
