### ISSUE TITLE
CMAKE error when building

### ISSUE THREAD

**Issue by ShawnP1337** [pmed/v8pp#183]
I am new to this v8pp module. When I run cmake .. I receive the following error. 

CMake Error at cmake/FindV8.cmake:82 (add_library):
  add_library cannot create ALIAS target "V8::V8" because target "V8::v8" is
  imported but not globally visible.
Call Stack (most recent call first):
  v8pp/CMakeLists.txt:9 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/usr/v8pp/out/CMakeFiles/CMakeOutput.log".

What am I doing wrong?

**Comment by uniqss** [comment]
If you are on windows, install a visual studio 2019 community or visual studio 2022 community, and open the v8pp.sln in the root directory, and F7 or click build, this solution will automatically install all libraries needed. This is the easiest way to make everything works.

**Comment by pmed** [comment]
Yes, prebuilt V8 library is required.
