### ISSUE TITLE
file missing config.hpp 

### ISSUE THREAD

**Issue by Eunsolfs** [pmed/v8pp#196]
config.hpp file is missing ,can`t compile

**Comment by F0RQU1N** [comment]
same problem

**Comment by Eunsolfs** [comment]
I changed the filename of config.hpp.in into config.hpp to solve this problem



---- Replied Message ----
| From | ***@***.***> |
| Date | 05/14/2023 13:05 |
| To | ***@***.***> |
| Cc | ***@***.***>、State ***@***.***> |
| Subject | Re: [pmed/v8pp] file missing config.hpp (Issue #196) |

same problem

**Comment by F0RQU1N** [comment]
> I changed the filename of config.hpp.in into config.hpp to solve this problem
> […](#)
> ---- Replied Message ---- | From | ***@***.***> | | Date | 05/14/2023 13:05 | | To | ***@***.***> | | Cc | ***@***.***>、State ***@***.***> | | Subject | Re: [pmed/v8pp] file missing config.hpp (Issue #196) | same problem — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***>

i tried already but got these errors
![image](https://github.com/pmed/v8pp/assets/108815933/c5d03807-bc06-4643-abf9-d887743436d9)

**Comment by Eunsolfs** [comment]
It’s not enough to just modify the file extension, you need to do other steps—perfect the parameters in the config.hpp file.

Below is the link of my config.hpp file, you can refer to

https://godbolt.org/z/3fY8G794K

**Comment by Eunsolfs** [comment]
> t’s not enough to just modify the file extension, you need to do other steps—perfect the parameters in the config.hpp file.
> 
> Below is the link of my config.hpp file, you can refer to
> 
> https://godbolt.org/z/3fY8G794K

t’s not enough to just modify the file extension, you need to do other steps—perfect the parameters in the config.hpp file.

Below is the link of my config.hpp file, you can refer to

https://godbolt.org/z/3fY8G794K

**Comment by Aincvy** [comment]
In my case, `#define V8PP_ISOLATE_DATA_SLOT 0`  is fine, but 33826 not.  

The code `std::cout << "number of slots: " << isolate->GetNumberOfDataSlots() << std::endl;`  gives me `number of slots: 4`
