### ISSUE TITLE
Build fails on systems with newer ICU

### ISSUE THREAD

**Issue by exploser** [pmed/v8pp#29]
Not really a big issue and I understand that the library was not tested on non-Ubuntu setups, but commit 5770abbe removed linking with icui18n and icuuc shipped with V8 which causes linking errors on systems with ICU 5.7 (such as Manjaro I'm currently on).

Building with V8 obtained from build-v8.sh and re-adding -licuuc -licui18n to LIBS works fine.

**Comment by pmed** [comment]
@exploser  thanks! I've added these ICU libraries into the Makefile.
