### ISSUE TITLE
Example in 'convert.md' does not work

### ISSUE THREAD

**Issue by jcmonnin** [pmed/v8pp#38]
The examples for user defined type do not work.

Problem is here:

    static bool is_valid(v8::Isolate*, v8::Handle<v8::Value> value)
    {
        return !value.IsEmpty() && value->IsArray() && value->Length() == 3;
    }

`v8::Value` has no method `Length()` (at least in recent v8 versions).

Related to that there is also the separate pull request about typos.

**Comment by pmed** [comment]
Hi!

Yes, the whole project documentation, and examples in particular, are quite incomplete. I will look through this and other examples, to check they work.

**Comment by jcmonnin** [comment]
Thanks for fixing the examples in the documentation.

**Comment by pmed** [comment]
Thanks for the bug catching :-)

**Comment by jcmonnin** [comment]
I think there are some other in the README.md:

```C++
// Memory for C++ class will remain when JavaScript object is deleted.
// v8pp::no_factory avoids creating any constructor for your C++ class from
// JavaScript, useful for classes you only wish to inject.
typedef v8pp::class_<my_class> my_class_wrapper(isolate);
v8::Handle<v8::Value> val = my_class_wrapper::reference_external(&my_class::instance());
// Assuming my_class::instance() returns reference to class
```

Should probably be something like:

```C++
// Memory for C++ class will remain when JavaScript object is deleted.
// Useful for classes you only wish to inject.
typedef v8pp::class_<my_class> my_class_wrapper(isolate);
v8::Handle<v8::Value> val = v8pp::class_<my_class>::reference_external(&my_class::instance());
// Assuming my_class::instance() returns reference to class
```

**Comment by pmed** [comment]
Yes, it should be, thanks!
