### ISSUE TITLE
Flexible callback argument support

### ISSUE THREAD

**Issue by tim-janik** [pmed/v8pp#49]
Is there a nbind::cbFunction equivalent in v8pp?
I.e. as described here: https://github.com/charto/nbind#callbacks

**Comment by tim-janik** [comment]
As tentative answer, v8pp supports v8::Local values as bound function arguments, so there's no problem binding e.g. the following method via set():
~~~~
void connect (v8::Local<v8::Function> v8value) {
  printf ("%s: expecting function: IsFunction=%d\n", __func__, v8value->IsFunction());
}
X_class.set ("connect", &Class::connect);
~~~~

**Comment by pmed** [comment]
Yes, that's right, you can use V8 values as function arguments and return values in v8pp.
