### ISSUE TITLE
class template has already been defined

### ISSUE THREAD

**Issue by damospiderman** [pmed/v8pp#5]
Using the most current stable version of v8 I get the follow errors

v8pp/convert.hpp(417): error C2953: 'v8pp::convert<v8::Local<T>,void>' : class template has already been defined
v8pp/convert.hpp(377) : see declaration of 'v8pp::convert<v8::Local<T>,void>'
v8pp/convert.hpp(449): error C2953: 'v8pp::is_wrapped_class<v8::Local<T>>' : class template has already been defined
v8pp/convert.hpp(446) : see declaration of 'v8pp::is_wrapped_class<v8::Local<T>>'

**Comment by pmed** [comment]
Yes, this is a known issue and it breaks Travis build :(

v8::Handle class template has been removed from V8 API and now it's an alias for v8::Local. Hence we got two v8pp::convert specializations for the single class.

But I thought this change is not in stable version. I'm thinking how to manage this with previous version, probably I will have to add those specializations depending on actual V8 version.

**Comment by damospiderman** [comment]
Hmmm well I think it's the stable build I'm using, I just grabbed v8 from git

I managed to remove the errors by commenting out the 2 classes with v8::handle but now I just get crashes in my app when I call set on a module. I might have to try and work out how to get an older build of v8

**Comment by pmed** [comment]
Fixed in b1b88c586de342c9ffbde8659d51f406692217e5
