### ISSUE TITLE
How to use ArrayBuffer with v8pp::class_ ?

### ISSUE THREAD

**Issue by pkhach** [pmed/v8pp#59]
Hello,

I would like to pass binary data to JavaScript and process them as ArrayBuffer (Uint8Array) in script.

How can I do this with v8pp?

```
struct X
{
	unsigned char* buffer;
};

// bind class
v8pp::class_<X> X_class(isolate);
X_class
	.set("buffer", ??????);
```

Thanks!

**Comment by pmed** [comment]
Hi @pkhach, You could try to write a [`v8pp::convert<X>`](https://github.com/pmed/v8pp/blob/master/docs/convert.md#user-defined-types) specialization that uses `v8::ArrayBuffer` for `X::buffer`
