### ISSUE TITLE
v8pp::from_v8 and std::vector<std::string>

### ISSUE THREAD

**Issue by vinnitu** [pmed/v8pp#7]
Can you create example of usage v8pp::from_v8?

thx

**Comment by pmed** [comment]
I'm going to add a wiki page about data conversion between C++ and V8. Currently please look at the [conversion tests](https://github.com/pmed/v8pp/blob/master/test/test_convert.cpp#L28) how to use them.

In brief, `std::vector` is converted to JS array with conversion for each item:

```c++
std::vector<std::string> strings = { "abc", "xyz" };

auto js_array = v8pp::to_v8(isolate, strings);  // would be ["abc", "xyz"] in JavaScript

// v8pp::from_v8 template function needs to know the destination type
auto strings2 = v8pp::from_v8< std::vector<std::string> >(isolate, js_array);

assert(strings == strings2);
```

**Comment by vinnitu** [comment]
thank You, I also found my mistake...
