### ISSUE TITLE
call_v8() will crash the V8?

### ISSUE THREAD

**Issue by VitaminCpp** [pmed/v8pp#73]
Do I miss something or is it possible that the V8 will crash if you're trying to call broken methods (e.g methods which are trying to call other undefined methods)?
I think "ToLocalChecked" is a bit dangerous here, because in this case the result will be empty, the V8 will crash and a v8::TryCatch should report an error.

I think this would solve this issue:
```
v8::Local<v8::Value> result:
func->Call(isolate->GetCurrentContext(), recv, arg_count, v8_args).ToLocal(&result);
```

The user than have to check if the result is valid and should do adequate error handling by his own?

**Comment by pmed** [comment]
Hi @VitaminCpp, 

thank you, it sounds reasonable. Do you have a minimal code sample that demonstrates this issue?

**Comment by VitaminCpp** [comment]
Hi @pmed,

thanks for the fast response!

Just try to call a JS function which itself tries to call a not existing function:
```
var func = function() {
	nonExistingFunc("foobar");
}

func();
```

```
v8::Script::Compile(...).ToLocal(&script);
script->Run(context).ToLocal(&result));
auto func = result.As<v8::Function>(...);

// Will crash as stated in v8.h:377!
func->Call(ctx.isolate()->GetCurrentContext(), func, 0, 0).ToLocalChecked();
```

I hope this helps?

**Comment by pmed** [comment]
Hi @VitaminCpp,

Fixed, thank you!

**Comment by VitaminCpp** [comment]
You're welcome! Keep up the great work! ;-)
