### ISSUE TITLE
Make "require" and "run" globals optional

### ISSUE THREAD

**Issue by VitaminCpp** [pmed/v8pp#75]
Hi,

IMHO these two global script exports should be made optional, because not everybody wants to allow users to call this methods. For me it's a big security issue, because my software operates on a virtual file system where scripts must be embedded into an encrypted archive.
Also I explicitly want to enable or disable certain script features, so "require" is currently a real show stopper for me.

So two possible solutions come into my mind:
- Allow/Disallow these methods by an additional constructor argument (e.g. v8pp::context(..., bool export_default_methods = true)).
- Use a global v8pp define to explicitly allow/disallow these methods (e.g. #define V8PP_ALLOW_DEFAULT_METHODS).

**Comment by pmed** [comment]
Hi,

Yes, these default global exports are too powerful. Frankly speaking, I use `v8pp::context` only in the test program, and other parts of the library do not depend on the `context` implementation at all.

So there is 3rd option: do not include `context.{h,c}pp` files into the library build.

I wouldn't like to break the library compatibility in the master branch, thus your 1st option with `v8p::context` constructor argument looks better.

**Comment by pmed** [comment]
Fixed in master branch

**Comment by VitaminCpp** [comment]
Hi,

thanks for the fast response! So you would suggest to not depend on v8pp::context at all?

**Comment by pmed** [comment]
This `v8pp::context` is a simple wrapper to create a `v8::Isolate` and `v8::Conext` instances. So yes, if you have your own V8 initiation code,  you might don't need the `v8pp::context`.

Anyways, I've added 3rd argument to the `v8pp::context` ctor, to make these global functions optional.

**Comment by VitaminCpp** [comment]
Alright that makes sense. So I will use my own context.
Thanks!
