### ISSUE TITLE
how to release memeory in member function?

### ISSUE THREAD

**Issue by gotomypc** [pmed/v8pp#8]
like the following code, how to release the char pointer str1?
```
#include <node.h>
#include <v8pp/module.hpp>

using namespace v8;

char const* Method() {
  char* str1 = new char[32];
  if (NULL != str1) strcpy(str1, "world");
  return str1;
}

void init(Handle<Object> exports) {
  v8pp::module addon(Isolate::GetCurrent());
  addon.set("hello", &Method);
  exports->SetPrototype(addon.new_instance());
}

NODE_MODULE(addon, init)
```

**Comment by pmed** [comment]
There will be a memory leak. The return value from `Method()` function will be converted into `v8::String` object, that manage its own copy of data.  Use `char const*` only for static string literals, otherwise return `std::string` objects.

**Comment by gotomypc** [comment]
Ok, thank you.  I use std::string to convert from char* to string, then free char*.
