### ISSUE TITLE
How to pass C++-only arguments (loggers, allocators,...) to V8 created objects

### ISSUE THREAD

**Issue by VitaminCpp** [pmed/v8pp#83]
I need a way to pass a logger and an allocator to each V8 created object like this:
```
MyLogger logger;
using MyClassWrapper = v8pp::class_<MyClass>;
MyClassWrapper uaNodeWrapper(isolate);
uaNodeWrapper
  .ctor<v8::FunctionCallbackInfo<v8::Value> const& args>([&](v8::FunctionCallbackInfo<v8::Value> const& args) -> MyClass* {
    return new MyClass(myLogger, args);
  })
  .set("method", &MyClass::myMethod)
  .set("value", v8pp::property(&MyClass::value, &MyClass::setValue));
```
But this doesn't work, because this factory method is a function pointer instead a function object.
So I want to inject C++-only references. Is there any way I can do this?

**Comment by pmed** [comment]
Hi @VitaminCpp 

I've fixed this issue in master branch.

**Comment by VitaminCpp** [comment]
Great!!! Thanks a lot @pmed!
