### ISSUE TITLE
How to call a destructor of an object class explicitly  

### ISSUE THREAD

**Issue by zxbzswxr** [pmed/v8pp#85]
I write an class with c++ ， and export it and use it as addons 
in Node.js  I create multiple objects , but  I find that the object call its destructor only when Node  exit,
So  even  the object is assigned to a local var ,  the object can not be released until  Node exit . 
Is there any advise or means that I can explicitly call the Destructor of an Object?

**Comment by pmed** [comment]
There is a [`v8pp::class_<T>::destroy_object(isolate, object_pointer)`](https://github.com/pmed/v8pp/blob/master/v8pp/class.hpp#L653) static function to destroy a wrapped C++ class `T` object.

**Comment by zxbzswxr** [comment]
@pmed Ok，I follow your advice and make it done !!!  Thank you very much, I appreciate you work extremely !!!!

**Comment by zxbzswxr** [comment]
So ,I can Close it this issue.
