### ISSUE TITLE
Does the class constructor must be this form ? void (*)(const v8::FunctionCallbackInfo<v8::Value>& args)????

### ISSUE THREAD

**Issue by zxbzswxr** [pmed/v8pp#87]
as title mentioned , if I have C++  class ,How can I pass difference parameters when calling a constructor of an object .....

**Comment by pmed** [comment]
Of course not, see example in documentation for `v8pp::class_`: https://github.com/pmed/v8pp/blob/master/docs/wrapping.md#v8ppclass_
